# Generated by Django 3.1.6 on 2021-12-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0003_auto_20211203_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='email',
        ),
    ]
