# Generated by Django 3.1.6 on 2021-12-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0006_auto_20211219_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='category',
            field=models.ManyToManyField(related_name='category', to='vimbiso.Category'),
        ),
    ]
