# Generated by Django 3.1.6 on 2021-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0007_auto_20211223_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='type_of_purchase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='item_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
