# Generated by Django 3.1.6 on 2021-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0008_auto_20211223_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
