# Generated by Django 3.1.6 on 2022-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0010_auto_20211224_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='block',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
