# Generated by Django 3.1.6 on 2022-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimbiso', '0012_auto_20220107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='tags',
            field=models.ManyToManyField(related_name='tag_company', to='vimbiso.Tags'),
        ),
    ]
